### PR TITLE
Avoid compilation error when using tasty 0.11.0.3 due to duplicate Sh…

### PR DESCRIPTION
**Pull request by sinelaw**
…ow instance for a -> b

### CODE REVIEW

**Comment by sinelaw** [comment]
See https://github.com/fpco/stackage/issues/1410

**Comment by kim** [comment]
Thanks.

**Comment by peti** [comment]
@kim, would you mind releasing a new version with that fix to Hackage?

**Comment by kim** [comment]
0.6.4 is available on hackage

**Pull request merged**
